### ISSUE TITLE
can not build

### ISSUE THREAD

**Issue by krsfrodaslz** [nybuxtsui/gowalk#1]
$ export GOPATH=$PWD/client
$ go build gowalk

# github.com/nybuxtsui/ca/third_party/github.com/jstemmer/pkcs10
client/src/github.com/nybuxtsui/ca/third_party/github.com/jstemmer/pkcs10/pkcs10.go:76: undefined: x509.ECDSAWithSHA1
client/src/github.com/nybuxtsui/ca/third_party/github.com/jstemmer/pkcs10/pkcs10.go:78: undefined: x509.ECDSAWithSHA256
client/src/github.com/nybuxtsui/ca/third_party/github.com/jstemmer/pkcs10/pkcs10.go:80: undefined: x509.ECDSAWithSHA384
client/src/github.com/nybuxtsui/ca/third_party/github.com/jstemmer/pkcs10/pkcs10.go:82: undefined: x509.ECDSAWithSHA512
client/src/github.com/nybuxtsui/ca/third_party/github.com/jstemmer/pkcs10/x509.go:67: undefined: x509.ECDSAWithSHA1
client/src/github.com/nybuxtsui/ca/third_party/github.com/jstemmer/pkcs10/x509.go:69: undefined: x509.ECDSAWithSHA256
client/src/github.com/nybuxtsui/ca/third_party/github.com/jstemmer/pkcs10/x509.go:71: undefined: x509.ECDSAWithSHA384
client/src/github.com/nybuxtsui/ca/third_party/github.com/jstemmer/pkcs10/x509.go:73: undefined: x509.ECDSAWithSHA512
client/src/github.com/nybuxtsui/ca/third_party/github.com/jstemmer/pkcs10/x509.go:91: undefined: x509.ECDSA
client/src/github.com/nybuxtsui/ca/third_party/github.com/jstemmer/pkcs10/x509.go:142: undefined: x509.ECDSA
client/src/github.com/nybuxtsui/ca/third_party/github.com/jstemmer/pkcs10/x509.go:142: too many errors
# github.com/BurntSushi/toml
client/src/github.com/BurntSushi/toml/encode.go:358: function ends without a return statement
client/src/github.com/BurntSushi/toml/encode.go:464: function ends without a return statement
client/src/github.com/BurntSushi/toml/encode.go:473: function ends without a return statement
client/src/github.com/BurntSushi/toml/lex.go:72: function ends without a return statement

**Comment by nybuxtsui** [comment]
x509是系统包
你的go环境是什么版本的？

**Comment by krsfrodaslz** [comment]
version 1.0.3. 
Solved by installing 1.3.3.
