### ISSUE TITLE
在Mac下添加了证书，Chrome可以打开google，但是safari始终不信任证书

### ISSUE THREAD

**Issue by viquu** [nybuxtsui/gowalk#5]
RT，在safari下打开google，就会出现一个选择证书的提示框，上方显示"www.google.com.hk"不接受“未知”的证书。 下方有一个证书列表，里面有出现我原来的Goagent证书，但是没有gowalk新增加的证书。
![2014-11-15 9 34 03](https://cloud.githubusercontent.com/assets/4003817/5057784/7af55758-6d0f-11e4-8ffc-127b7dba690f.png)

**Comment by nybuxtsui** [comment]
原因是证书没有导入到系统中
程序所在目录下有个叫certs的目录，目录中有个叫ca.crt的文件
1.如果只在safari中做代理，只需将该证书导入到safari中，在chrome中称为"授权中心"，safari叫什么名字不清楚了
2.如果要在全局做代理，参考了goagent的代码，可以在certs目录下面执行的命令：
security find-certificate -a -c "gowalk" | grep "gowalk" >/dev/null || security add-trusted-cert -d -r trustRoot -k "/Library/Keychains/System.keychain" "ca.crt"
参考代码:
https://github.com/goagent/goagent/blob/40142bfbd4829aaea9068a497cf6d96076f1264e/local/proxylib.py#L287

**Comment by viquu** [comment]
证书我是手动加的，因为原来装过goagent,所以证书这步我没有漏掉。原来goagent没有问题。mac下有个钥匙串的管理，里面可以加证书。

**Comment by nybuxtsui** [comment]
这个没办法帮忙了，因为没有mac。我在linux和windows下面没问题。如果找到答案的话，希望能来留个答案，谢谢

**Comment by nybuxtsui** [comment]
看看这个有帮助吗？

# https://code.google.com/p/goagent/issues/detail?id=18567&colspec=ID%20Opened%20Reporter%20Modified%20Summary%20Stars

好吧，解决了这个问题，分享一下。
在mac下导入证书后在钥匙串访问中再次双击导入的goagent证书，在弹出的窗口中点击信任展开，然后在信任里面，勾选最上面的使用此证书时 选中始终信任。
注意：导入时候的信任，系统默认只信任了基本策略，其他没设置

**Comment by viquu** [comment]
3Q，始终信任这步我前面是做过的。
另外，昨晚还发现一个问题。在打开gowalk以后，chrome右上角的设置，就是那个三条横框“三”，图标会变成黄色。打开一看，发现是要我重新登陆同步帐号。
而一旦我关闭gowalk， 我那个原先登陆着的帐号马上就回来了。好奇怪的说~~~

**Comment by nybuxtsui** [comment]
是的，这个问题我这里也有，从日志上看，是chrome在启动的时候https握手失败，应该是启动的时候没信任这个证书。但是重新登陆就ok了，这个目前还没想出解决办法，只能看看chromium的源代码，看看他启动时候的证书库是怎么处理的，目前还没线索。

**Comment by nybuxtsui** [comment]
最新版本已解决，bypass https站点直连，chrome握手没有问题了

**Comment by viquu** [comment]
赞，晚上回去试试。
